[package]
name = "bevy_3d_sandbox"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.4"
bevy = "0.17"
bevy_panorbit_camera = "0.33"
bevy_skein = "0.4"
bevy-tnua = "0.26"
bevy-tnua-avian3d = "0.8"
